version: '3.8'

services:
  rotary-gallery:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./albums:/app/albums:ro
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/dist:/usr/share/nginx/html:ro
    depends_on:
      - rotary-gallery
    restart: unless-stopped
